<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Postiz.NET.AspNetCore</PackageId>
    <Description>ASP.NET Core health checks for Postiz.NET.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Postiz.NET/Postiz.NET.csproj" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
